# Generated by Django 5.0.3 on 2024-03-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ilustration', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MagicElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ilustration', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ilustration', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lore', models.TextField()),
                ('ilustration', models.ImageField(blank=True, null=True, upload_to='')),
                ('level', models.IntegerField()),
                ('movement', models.FloatField()),
                ('health', models.IntegerField()),
                ('passivePerception', models.IntegerField()),
                ('armorClass', models.IntegerField()),
                ('maxWeight', models.FloatField()),
                ('currentWeight', models.FloatField()),
                ('weightStatus', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
                ('expertises', models.ManyToManyField(to='app_legends.characterexpertise')),
            ],
        ),
        migrations.AddField(
            model_name='characterexpertise',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.expertise'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('weight', models.FloatField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.itemtype'),
        ),
        migrations.CreateModel(
            name='MagicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('elements', models.ManyToManyField(to='app_legends.magicelement')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='magicGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_legends.magicgroup'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='app_legends.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.specialization'),
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('castingTime', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('manaCost', models.IntegerField()),
                ('health', models.IntegerField(blank=True, null=True)),
                ('heal', models.CharField(blank=True, max_length=255, null=True)),
                ('damage', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('damageType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_legends.damagetype')),
                ('elements', models.ManyToManyField(to='app_legends.magicelement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.magicgroup')),
                ('ingredientCost', models.ManyToManyField(to='app_legends.item')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(to='app_legends.spell'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goldCoins', models.IntegerField()),
                ('silverCoins', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ilustration', models.ImageField(blank=True, null=True, upload_to='')),
                ('range', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('baseDamage', models.CharField(max_length=255)),
                ('damageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.damagetype')),
                ('traits', models.ManyToManyField(to='app_legends.weapontrait')),
                ('weaponType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.weapontype')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('weight', models.FloatField()),
                ('finalDamage', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
                ('expertises', models.ManyToManyField(to='app_legends.expertise')),
                ('tools', models.ManyToManyField(to='app_legends.item')),
                ('elements', models.ManyToManyField(to='app_legends.magicelement')),
                ('weapons', models.ManyToManyField(to='app_legends.weapontype')),
            ],
        ),
    ]
