# Generated by Django 5.0.3 on 2024-03-12 22:26

import utils.legends_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ilustration',
            field=models.ImageField(blank=True, null=True, upload_to=utils.legends_upload_paths.character_ilustration_upload),
        ),
        migrations.AlterField(
            model_name='item',
            name='ilustration',
            field=models.ImageField(blank=True, null=True, upload_to=utils.legends_upload_paths.item_ilustration_upload),
        ),
        migrations.AlterField(
            model_name='race',
            name='ilustration',
            field=models.ImageField(blank=True, null=True, upload_to=utils.legends_upload_paths.race_ilustration_upload),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='ilustration',
            field=models.ImageField(blank=True, null=True, upload_to=utils.legends_upload_paths.specialization_ilustration_upload),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ilustration',
            field=models.ImageField(blank=True, null=True, upload_to=utils.legends_upload_paths.weapon_ilustration_upload),
        ),
    ]
