# Generated by Django 5.0.3 on 2024-03-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0004_character_title_alter_character_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='mana',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='Modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_legends.modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='Modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_legends.modifier'),
            preserve_default=False,
        ),
    ]
