# Generated by Django 5.0.3 on 2024-03-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0006_character_editor_alter_character_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='armorClass',
        ),
        migrations.RemoveField(
            model_name='character',
            name='currentWeight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='maxWeight',
        ),
        migrations.RemoveField(
            model_name='character',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='character',
            name='passivePerception',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weightStatus',
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.FloatField()),
                ('health', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('passivePerception', models.IntegerField()),
                ('armorClass', models.IntegerField()),
                ('maxWeight', models.FloatField()),
                ('currentWeight', models.FloatField()),
                ('weightStatus', models.CharField(max_length=255)),
                ('atributes', models.ManyToManyField(blank=True, to='app_legends.characterattribute')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_legends.character')),
            ],
        ),
    ]
