# Generated by Django 5.0.3 on 2024-03-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0007_remove_character_armorclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexpertise',
            name='character',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app_legends.character'),
            preserve_default=False,
        ),
    ]
