# Generated by Django 5.0.3 on 2024-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0008_characterexpertise_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterattribute',
            name='remaining',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
