# Generated by Django 5.0.3 on 2024-03-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0010_race_age_race_attributeincrease1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='skills',
            field=models.ManyToManyField(blank=True, to='app_legends.skill'),
        ),
        migrations.AlterField(
            model_name='race',
            name='magicAffinity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_legends.magicgroup'),
        ),
    ]
