# Generated by Django 5.0.3 on 2024-03-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0011_race_skills_alter_race_magicaffinity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='race',
            name='normalCharCanUse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='normalCharCanUse',
            field=models.BooleanField(default=False),
        ),
    ]
