# Generated by Django 5.0.3 on 2024-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0012_alter_race_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='currentEP',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='currentHP',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='maxEP',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='maxHP',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='remainingPoints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='attributeIncrease1',
            field=models.CharField(blank=True, choices=[('Corpo', 'Corpo'), ('Destreza', 'Destreza'), ('Conhecimento', 'Conhecimento'), ('Mente', 'Mente'), ('Social', 'Social')], max_length=12, null=True),
        ),
    ]
