# Generated by Django 5.0.3 on 2024-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0013_character_currentep_character_currenthp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armorClass',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
    ]
