# Generated by Django 5.0.3 on 2024-03-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0015_rename_mana_characterstats_maxep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='expertises',
        ),
        migrations.AddField(
            model_name='specialization',
            name='expertises',
            field=models.ManyToManyField(blank=True, to='app_legends.expertise'),
        ),
    ]
