# Generated by Django 5.0.3 on 2024-03-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0016_remove_specialization_expertises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='baseEP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='baseHP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='healDice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='levelHP',
            field=models.IntegerField(),
        ),
    ]
