# Generated by Django 5.0.3 on 2024-03-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0018_skill_skillcost_skill_skilltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='healDice',
            field=models.CharField(max_length=255),
        ),
    ]
