# Generated by Django 5.0.3 on 2024-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0020_alter_characterstats_armorclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficiency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characterexpertise',
            name='proficient',
            field=models.BooleanField(default=False),
        ),
    ]
