# Generated by Django 5.0.3 on 2024-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0022_rename_baseep_specialization_basemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexpertise',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
