# Generated by Django 5.0.3 on 2024-04-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0023_characterexpertise_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='elements',
        ),
        migrations.AddField(
            model_name='spell',
            name='firstElement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_element', to='app_legends.magicelement'),
        ),
        migrations.AddField(
            model_name='spell',
            name='secondElement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_element', to='app_legends.magicelement'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spellType',
            field=models.CharField(choices=[('Simples', 'Simples'), ('Intermediária', 'Intermediária'), ('Avançada', 'Avançada')], default='Simples', max_length=13),
        ),
        migrations.AddField(
            model_name='spell',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_legends.spellorigin'),
        ),
    ]
