# Generated by Django 5.0.3 on 2024-04-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0025_spell_spelltier_alter_spell_spelltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='spellExpertise',
            field=models.CharField(choices=[('Arcanismo', 'Arcanismo'), ('Crença', 'Crença'), ('Performance', 'Performance')], default='Arcanismo', max_length=11),
        ),
    ]
