# Generated by Django 5.0.3 on 2024-04-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0027_spell_areaofeffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='areaOfEffect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range',
            field=models.FloatField(),
        ),
    ]
