# Generated by Django 5.0.3 on 2024-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0029_remove_weapon_weapontype_remove_weapon_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontrait',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
