# Generated by Django 5.0.3 on 2024-04-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0031_remove_weapontrait_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='range',
            new_name='combat',
        ),
    ]
