# Generated by Django 5.0.3 on 2024-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0032_rename_range_weapon_combat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['rarity', 'type', 'combat']},
        ),
        migrations.AlterModelOptions(
            name='weapontrait',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='weapon',
            name='ammunition',
            field=models.ManyToManyField(blank=True, to='app_legends.item'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='guardBlock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='magazine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='reloadTime',
            field=models.CharField(blank=True, choices=[('Rápido', 'Rápido'), ('Médio', 'Médio'), ('Lento', 'Lento')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='versatileDamage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
