# Generated by Django 5.0.3 on 2024-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0033_alter_modifier_options_alter_weapon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='modifier',
            name='manaCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
