# Generated by Django 5.0.3 on 2024-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0034_alter_damagetype_options_modifier_manacost'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='guardBlock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='versatileDamage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
