# Generated by Django 5.0.3 on 2024-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0035_modifier_guardblock_modifier_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['type', 'name', 'cost']},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['baseHP', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['combat', 'rarity', 'type', 'name']},
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='requiredElement',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='requiredMagicGroup',
        ),
        migrations.AddField(
            model_name='specialization',
            name='requiredElements',
            field=models.ManyToManyField(blank=True, to='app_legends.magicelement'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='startingItems',
            field=models.ManyToManyField(blank=True, related_name='items', to='app_legends.item'),
        ),
        migrations.RemoveField(
            model_name='race',
            name='magicAffinity',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='startingTools',
            field=models.ManyToManyField(blank=True, related_name='tools', to='app_legends.item'),
        ),
        migrations.AddField(
            model_name='race',
            name='magicAffinity',
            field=models.ManyToManyField(blank=True, to='app_legends.magicelement'),
        ),
    ]
