# Generated by Django 5.0.3 on 2024-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0036_alter_item_options_alter_modifier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['-baseHP', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['-combat', 'rarity', 'type', 'name']},
        ),
        migrations.AddField(
            model_name='armor',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='immunityDamages',
            field=models.ManyToManyField(blank=True, related_name='immunity_dmg', to='app_legends.damagetype'),
        ),
        migrations.AddField(
            model_name='armor',
            name='resistedDamages',
            field=models.ManyToManyField(blank=True, related_name='resisted_dmg', to='app_legends.damagetype'),
        ),
        migrations.AddField(
            model_name='armor',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armor',
            name='immunityEffects',
            field=models.ManyToManyField(blank=True, related_name='immunity_effect', to='app_legends.effect'),
        ),
        migrations.AddField(
            model_name='armor',
            name='resistedEffects',
            field=models.ManyToManyField(blank=True, related_name='resisted_effect', to='app_legends.effect'),
        ),
    ]
