# Generated by Django 5.0.3 on 2024-05-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0037_effect_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_legends.armor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
