# Generated by Django 5.0.3 on 2024-05-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0038_character_armor_alter_character_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterweapon',
            name='Modifier',
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='modifierTraits',
            field=models.ManyToManyField(blank=True, to='app_legends.weapontrait'),
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='name',
            field=models.CharField(default='Arma', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterweapon',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_legends.modifier'),
        ),
    ]
