# Generated by Django 5.0.3 on 2024-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0041_alter_characterweapon_finaldamage'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='atackRoll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
