# Generated by Django 5.0.3 on 2024-05-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0042_characterweapon_atackroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterweapon',
            old_name='atackRoll',
            new_name='attackRoll',
        ),
    ]
