# Generated by Django 5.0.3 on 2024-06-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0044_rename_range_weapon_shotrange_weapon_combatrange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['name', 'cost']},
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='guardBlock',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='range',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='traitsAdded',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='type',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='versatileDamage',
        ),
    ]
