# Generated by Django 5.0.3 on 2024-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0045_alter_modifier_options_remove_modifier_guardblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='combatRange',
            field=models.FloatField(blank=True, default=1.5, null=True),
        ),
    ]
