# Generated by Django 5.0.3 on 2024-06-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0046_alter_weapon_combatrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='combatRange',
            field=models.FloatField(default=1.5),
        ),
    ]
