# Generated by Django 5.0.3 on 2024-06-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0048_remove_characterweapon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterweapon',
            name='damageType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_legends.damagetype'),
        ),
    ]
