# Generated by Django 5.0.3 on 2024-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legends', '0049_characterweapon_damagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterweapon',
            name='modifierTraits',
        ),
    ]
