# Generated by Django 5.0.3 on 2024-03-12 22:34

import utils.main_upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpgsystem',
            name='ilustration',
            field=models.ImageField(upload_to=utils.main_upload_paths.systems_ilustration_upload),
        ),
    ]
