# Generated by Django 5.0.3 on 2024-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_rpgsystem_ilustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpgsystem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app_main.tag'),
        ),
    ]
